# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
 use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ZuperForms' do
  pod 'SNHttpRequest'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'EmptyStateKit'
end

  target 'ZuperFormsExample' do
  pod 'SNHttpRequest'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'EmptyStateKit'
end
